# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NodewiseRegression <- function(y, response, covariates, gmixPath, sglmixPath, lambdaPath = as.numeric( c()), nlambda = 100L, lambdaFactor = 1e-4, maxit = 1000L, tol = 1e-8, verbose = FALSE) {
    .Call('_ncagr_NodewiseRegression', PACKAGE = 'ncagr', y, response, covariates, gmixPath, sglmixPath, lambdaPath, nlambda, lambdaFactor, maxit, tol, verbose)
}

